apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.applicationName}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: {{.Values.applicationName}}
  name: {{.Values.applicationName}}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - list
      - patch
      - create
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.applicationName}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.applicationName}}
subjects:
  - kind: ServiceAccount
    name: {{.Values.applicationName}}
    namespace: {{.Values.namespace}}
