apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imagepullsecret-patcher
  namespace: imagepullsecret-patcher
spec:
  encryptedData:
    .dockerconfigjson: AgBF9FWH9HuzLrGkpDXjCXhIJUa9t1d1Sk11jkJfNKlP/PJ1dGSWoLN5Bqdb3MQS5qy7TkGiZnL28K06K99qlnPePw8q5LyLF+b4nYHpW1LrmzCWyh1DbO4x3ZwnMmKooEGYAtPlpKMf2NF0LLNqmOPoG/8aay7ONUhsymgqccSi9SlyhC0H7pPcAu8Y0dkvz2l4ecvLaZA6FJwZWbdVfjX1pUYG4yPrEGQB0WbYrv2f7xyLUgluzzVFwyKZxtsMuDRnuQ/W8zM1CGPSN1VEX3GwuFXomcE7em1gd3bxTWMMwfm18r5CvtYTyGbzzBQ7+csJ2TzT9aMR8zBeMRcix/cpDUHg4z5pLYSMuBdVWhdZf0udOz4IroiSF6b01g+gO4fY4MLo3XeOW3j2bHLs3RD4o/lb2Ae5JVmac0jUeiqUny1X+DUX/sLaW+6MaS6jq8WPW/RxA1AR5AX9mOdreDzlmhJrXtbvD961xeV8CAG+AEkwZKXQ8pzW0GtA6N9lGjK0SQza4Ub3HMNFaEOtxeN2XKY3ZM1GVK8lxjh1XemxJW0AXk1HCkugf0GJHi5o629q6BH1Cj8Zrv2cCFaXfW/unBIlCchdFS0EPTxodpTPqFFa7RWnibcCLPCqUh+CYWCxcuZAvw5gMWsSOH/W6AhE3KoOwg/r1Byygb3ze3GsMftZ3jraudx/qlJ90XGnLo5Wu6l4Zl9qffkMNrgQRomFMtF0Bmn1+Ghxugt2VXKlN8ocPfDEeCiJpGu/x3x8ev0D2/FLo6Ndp0ltte1pp7/6jp1AaXcpDQWwvc8eXmr4z710clvxiJoxk9fP94deSSLECzJypcKoL7A2hT7+7oTZPtRsf+TLLnNlmfZg/3DfMHxrxVZMOaFVAwoIYz13curZSYT+8U+Czw7heU0xw/D8iYrpCsWbmw/8pwBjWUEAxmZ1G4h3N2RZpaEFC1Uaq9jZm/PtGg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      creationTimestamp: null
      name: imagepullsecret-patcher
      namespace: imagepullsecret-patcher
    type: kubernetes.io/dockerconfigjson
