apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imagepullsecret-patcher
  namespace: imagepullsecret-patcher
spec:
  encryptedData:
    .dockerconfigjson: AgClg7t5r0kSw3ZxBwc4pAjSEI0xM5/d3H2Go2WUQCGsCfpPIl0I/wPByU2yxAOur8ajnySRkYi+3DtxwrMDSYD7MnFLv8reRV5O318KdOyKRRpklvKVF6gWt31Ax9zCWOSutEJnxHuMtvd4Y2+YZFfWZfy7mO9QiRpweQPBUIwb6KjQwwPZdhZc1K7mXiGrixLrm1hcQHH6bq1qzhmgrgJeMSWPn2IfOvBqOohDT0LsYKtdbIl2tck/r2WwToMX5qYQ5qK6c58Qo8/gvQO8RdSW5RT0Gc8Q+JM2isl91OrXf9Y9N+maGszM7cNBNnRKj+7LvGZe/GvbrAu/GZ2f6XSGPVgul9kDW80RMgAKjPpmKTmKdK293Ik37Vo+py1bk0cvVv5B1RjbK7ZDmqYCnVvfO9OdeSgPZiMwZCM6eIOYePt7zPDL7fliq0EnCmLDCxnsdDAd16jWRKDk1AHSys555zCuWcrYh5TFBoChVV72z/HOMYIv9BdJfiEfar5mKkkXHH8Ly9tocEa7vQ3yA6ttwKO8AHySZ0IYGLL/V9N2aD0hno37LLTHALLzDUhX20FG6Mlvh2NcRm2Vag3TV2Bv6tPKnivL7BFrcTDsQ/hsdyBM2Ns2mbj2ZWwj8P5TmrSKj3Gp9RkFsW/arX/09of8475YtEINbmMUBdFJTbeJzT8SMDmQxsvd9QnK6PNZp+VFWZJ4pBlsPQQrwZ8LrwieapsRzTRJI6aelfY5kaXcAriHj5xSspepMZeO2/z3veEGOjs44dlEhEbuVKLzYYS9S+mhkmpm9cf/bIE98MS8uCK41UqL9EyJg3MIoi0l82fxMO1xP9wqsB0NWUBvTlhToNmLNXcEjAllkvi0TWlD9nlwfEkBrOVvqUVHthDS5yK6IgqyNVzb9UpsRXIPZex4RMAaH8RXvm7IxmS0NB+UwotjG4xvz9lEJA+OigQKODkpzelHmg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      creationTimestamp: null
      name: imagepullsecret-patcher
      namespace: imagepullsecret-patcher
    type: kubernetes.io/dockerconfigjson
